[app]
tick_rate = 20

[window]
width = 800
height = 600

[graphics]
backend = "Metal" # Metal, Vulkan, DX12

# Backquote, Backslash, BracketLeft, BracketRight, Comma,
# Digit0, Digit1, Digit2, Digit3, Digit4, Digit5, Digit6, Digit7, Digit8, Digit9,
# Equal, IntlBackslash, IntlRo, IntlYen,
# Key*, A..Z; Numpad*, 0..9
# Minus, Period, Quote, Semicolon, Slash, AltLeft, AltRight, Backspace, CapsLock, ContextMenu, ControlLeft, ControlRight, Enter,
# SuperLeft, SuperRight, ShiftLeft, ShiftRight, Space, Tab, Convert, KanaMode, Lang1, Lang2, Lang3, Lang4, Lang5, NonConvert, Delete, End, Help, Home, Insert, PageDown, PageUp,
# ArrowDown, ArrowLeft, ArrowRight, ArrowUp, NumLock,
# NumpadAdd, NumpadBackspace, NumpadClear, NumpadClearEntry, NumpadComma, NumpadDecimal, NumpadDivide, NumpadEnter, NumpadEqual, NumpadHash, NumpadMemoryAdd, NumpadMemoryClear, NumpadMemoryRecall, NumpadMemoryStore, NumpadMemorySubtract, NumpadMultiply, NumpadParenLeft, NumpadParenRight, NumpadStar, NumpadSubtract,
# Escape, Fn, FnLock, PrintScreen, ScrollLock, Pause, BrowserBack, BrowserFavorites, BrowserForward, BrowserHome, BrowserRefresh, BrowserSearch, BrowserStop, Eject,
# LaunchApp1, LaunchApp2, LaunchMail,
# MediaPlayPause, MediaSelect, MediaStop, MediaTrackNext, MediaTrackPrevious,
# Power, Sleep, AudioVolumeDown, AudioVolumeMute, AudioVolumeUp, WakeUp,
# Meta, Hyper, Turbo, Abort, Resume, Suspend, Again, Copy, Cut, Find, Open, Paste, Props, Select, Undo,
[keybinds]
player_left = "KeyA"
player_right = "KeyD"
player_up = "KeyW"
player_down = "KeyS"
